app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');



Route::group(['middleware' => ['auth'], 'prefix' => "admin/clients", 'as' => "admin.clients."], function () {
    Route::get('/', 'clientController@index')->name('index');
    Route::delete('{id}/delete', 'clientController@delete')->name('delete')->middleware('can:super_user');
    Route::get('{id}/edit', 'clientController@edit')->name('edit');
    Route::get('{id}/profile', 'clientController@profile')->name('profile');
    Route::get('init', 'clientController@init')->name('init');
    Route::post('save', 'clientController@save')->name('save');

});

Route::group(['middleware' => ['auth','can:super_user'], 'prefix' => "admin/employees", 'as' => "admin.employees."], function () {
    Route::get('/', 'employeeController@index')->name('index');
    Route::delete('{id}/delete', 'employeeController@delete')->name('delete');
    Route::get('{id}/edit', 'employeeController@edit')->name('edit');
    Route::get('{id}/profile', 'employeeController@profile')->name('profile');
    Route::get('init', 'employeeController@init')->name('init');
    Route::post('save', 'employeeController@save')->name('save');

});
Route::group(['middleware' => ['auth','can:super_user'], 'prefix' => "admin/coins", 'as' => "admin.coins."], function () {
    Route::get('/', 'coinController@index')->name('index');
    Route::delete('{id}/delete', 'coinController@delete')->name('delete');
    Route::get('{id}/edit', 'coinController@edit')->name('edit');
    Route::get('init', 'coinController@init')->name('init');
    Route::post('save', 'coinController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/instructors", 'as' => "admin.instructors."], function () {
    Route::get('/', 'instructorController@index')->name('index');
    Route::delete('{id}/delete', 'instructorController@delete')->name('delete');
    Route::delete('{id}/delete_document', 'instructorController@deleteDocument')->name('delete_document');
    Route::get('{id}/edit', 'instructorController@edit')->name('edit');
    Route::get('init', 'instructorController@init')->name('init');
    Route::get('init_document', 'instructorController@init_document')->name('init_document');
    Route::post('save', 'instructorController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/courses", 'as' => "admin.courses."], function () {
    Route::get('/', 'courseController@index')->name('index');
    Route::delete('{id}/delete', 'courseController@delete')->name('delete');
    Route::get('{id}/edit', 'courseController@edit')->name('edit');
    Route::get('init', 'courseController@init')->name('init');
    Route::post('save', 'courseController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/places", 'as' => "admin.places."], function () {
    Route::get('/', 'placeController@index')->name('index');
    Route::delete('{id}/delete', 'placeController@delete')->name('delete');
    Route::get('{id}/edit', 'placeController@edit')->name('edit');
    Route::get('init', 'placeController@init')->name('init');
    Route::post('save', 'placeController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/schedules", 'as' => "admin.schedules."], function () {
    Route::get('/', 'scheduleController@index')->name('index');
    Route::post('/recommend', 'scheduleController@recommend')->name('recommend');
    Route::delete('{id}/delete', 'scheduleController@delete')->name('delete');
    Route::delete('schedule_day/{id}/delete', 'scheduleController@deleteDay')->name('delete');
    
    Route::get('{id}/edit', 'scheduleController@edit')->name('edit');
    Route::get('init', 'scheduleController@init')->name('init');
    Route::post('save', 'scheduleController@save')->name('save');
    Route::get('/{id}/manage', 'scheduleController@manage')->name('manage');
    Route::post('update_interested_status', 'scheduleController@update_interested_status')->name('update_interested_status');
    Route::post('add_payment', 'scheduleController@add_payment')->name('add_payment');
    Route::get('/{schedule_id}/{user_id}/payment_history', 'scheduleController@payment_history')->name('payment_history');
    Route::get('/{user_id}/cancel', 'scheduleController@cancel')->name('cancel')->middleware('can:super_user');
    Route::get('/{schedule_id}/end_transactions', 'scheduleController@endTransactions')->name('end_transactions')->middleware('can:super_user');
    Route::get('/{schedule_id}/reopen_transactions', 'scheduleController@reOpenTransactions')->name('reopen_transactions')->middleware('can:super_user');
    
    
    

});


Route::group(['middleware' => ['auth'], 'prefix' => "admin/consultations", 'as' => "admin.consultations."], function () {
    Route::get('/', 'consultationController@index')->name('index');
    Route::delete('{id}/delete', 'consultationController@delete')->name('delete');
    Route::get('{id}/edit', 'consultationController@edit')->name('edit');
    Route::get('pricing', 'consultationController@pricing')->name('pricing')->middleware('can:super_user');
    Route::post('init', 'consultationController@init')->name('init');
    Route::post('save', 'consultationController@save')->name('save');
    Route::post('save_pricing', 'consultationController@save_pricing')->name('save_pricing')->middleware('can:super_user');
    Route::post('save_audio', 'consultationController@save_audio')->name('save_audio');
    Route::post('add_payment', 'consultationController@add_payment')->name('add_payment');
    Route::post('add_reply', 'consultationController@add_reply')->name('add_reply');
    Route::get('/{consultation_id}/end_transactions', 'consultationController@endTransactions')->name('end_transactions')->middleware('can:super_user');
    Route::get('/{consultation_id}/reopen_transactions', 'consultationController@reOpenTransactions')->name('reopen_transactions')->middleware('can:super_user');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/expenses", 'as' => "admin.expenses."], function () {
    Route::get('/', 'expenseController@index')->name('index');
    Route::delete('{id}/delete', 'expenseController@delete')->name('delete');
    Route::get('{id}/edit', 'expenseController@edit')->name('edit');
    Route::get('init', 'expenseController@init')->name('init');
    Route::post('save', 'expenseController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/reports", 'as' => "admin.reports."], function () {
    Route::get('/', 'reportController@index')->name('index');
    

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/transactions", 'as' => "admin.transactions."], function () {
    Route::delete('{id}/delete', 'transactionController@delete')->name('delete');
    
    Route::get('/{stuff_id}/{stuff_identifier}/{user_id}/payment_history', 'transactionController@payment_history')->name('payment_history');
    
    

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
Route::auth();

app/Http/Controllers/clientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Schedule;
use App\Course;
use App\Consultation;
use DB;
use App\Users_schedule;

use App\Http\Requests;
use Auth;

class clientController extends Controller
{
    public function __construct(){
		$this->logged_user = Auth::user();

	}
    public function index() {
        $clients = User::where('admin_show',1)->where('role_id',4)->get();
        $schedules = Schedule::where('admin_show',1)->get();
        $courses = Course::where('admin_show',1)->get();
        $data = [];
        $data['partialView'] = 'clients.list';
        $data['clients'] = $clients; 
        $data['schedules'] = $schedules; 
        $data['courses'] = $courses; 
        return view('clients.base', $data);
    }

    public function init(){
    	$client = new User();
    	$client->save();
    	return redirect('/admin/clients/'.$client->id.'/edit');
    }

    public function edit($id){
    	$client =  User::find($id);
    	$clients = User::where('admin_show',1)->where('role_id',4)->where('id','!=',$id)->get();
        $mothers = User::where('admin_show',1)->where('role_id',4)->where('gender','Female')->where('id','!=',$id)->get();
        $fathers = User::where('admin_show',1)->where('role_id',4)->where('gender','Male')->where('id','!=',$id)->get();
        $data = [];
        $data['clients'] = $clients;
        $data['client'] = $client;
        $data['mothers'] = $mothers; 
        $data['fathers'] = $fathers;
        $data['partialView'] = 'clients.form';
        return view('clients.base', $data);
    }

    public function save(Request $request){
        $data = $request->input();
        //Validations
        $check_email = User::where('email',$data['email'])->where('id','!=',$data['id'])->count();
        if($check_email !=0){
            $data = [];
            $data['status'] = 'error';
            
            $data['msg'] = "Email already exists";
            return response()->json(
                        $data
            );
        }
        $client = User::find($data['id']);
        $data['admin_show'] =1;
        $data['role_id'] =4;
        unset($data['password2']);
        if($data['date_of_birth'] != ""){
            $data['date_of_birth'] =date("Y-m-d",strtotime($data['date_of_birth']));
        }else{
            $data['date_of_birth'] = Null;    
        }
        if($data['joining_date'] != ""){
            $data['joining_date'] =date("Y-m-d",strtotime($data['joining_date']));
        }else{
            $data['joining_date'] = Null;    
        }
        

        if($client->update($data)){
            $data = [];
            $data['status'] = 'success';
            $data['page'] = '/admin/clients';
            $data['msg'] = "Saved Successfully";
            return response()->json(
                        $data
            );  
        }else{
        	$data = [];
            $data['status'] = 'error';
            $data['page'] = 'none';
            $data['msg'] = "There was an error";
            return response()->json(
                        $data
            );  

        }
    }

    public function profile($id){
        $client =  User::find($id);
        $children =  User::where('mother_id',$id)->orWhere('father_id',$id)->get();
        $consultations = Consultation::where('client_id',$id)->get();
        $clients = 
            Users_schedule::join('users', 'users.id', '=', 'users_schedules.user_id')
            ->join('schedules', 'users_schedules.schedule_id', '=', 'schedules.id')
            ->leftJoin('courses', 'schedules.course_id', '=', 'courses.id')
            ->leftJoin('places', 'schedules.place_id', '=', 'places.id')
            
            ->leftJoin('transactions', function($join)
                         {
                             $join->on( 'transactions.user_id', '=', 'users.id');
                             $join->on('transactions.schedule_id', '=', 'schedules.id');
                             
                         })

            ->where('users.id',$id)
            
            ->groupBy('transactions.schedule_id')
            ->select('users_schedules.*', 'courses.name', 'places.name as place','schedules.start_date', 'users.email','users.phone','users.points_balance' ,
                DB::raw('sum(amount) as payment')
                )
            ->get();
        $data = [];
        $data['clients'] = $clients;
        $data['client'] = $client;
        $data['consultations'] = $consultations;
        $data['children'] = $children;
        $data['partialView'] = 'clients.profile';
        return view('clients.base', $data);
    }
        

    
    public function delete($id){
       $delete = User::find($id)->delete();
    }
}

resources/views/clients/base.blade.php
<?php 
	$i ="clients" ; $j = "";
 ?>
@extends('admin.master')
@section('plugins_css')
<link href="/assets/admin/pages/css/profile.css" rel="stylesheet" type="text/css"/>

<link href="/assets/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>

@stop

@section('plugins_js')

@stop

@section('page_js')

@endSection

@section('add_inits')

@stop

@section('title')
Clients
@stop

@section('page_title')

@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/clients/form.blade.php
<form action="{{route('admin.clients.save')}}" method="post" class="ajax_form j-forms larajsval form" id="main-form" novalidate>
    <div class="header">
        <p>
             @if(empty($client->name))<i class="fa fa-user"></i> New client @else <i class="fa fa-user"></i> {{$client->name}} @endif
        </p>
    </div>

    <div class="content">
        
            
            
            
            
            
            <div class="unit">
                <label class="label">Gender</label>
                <label class="input select">
                    <select name="gender" data-validation="required" data-name="Gender" class="form-control" >
                        <option value="">Select Gender</option>
                        
                            <option  value="Male" <?php if( $client->gender == "Male"){?>selected<?php ;}?>>Male</option>
                            <option  value="Female" <?php if( $client->gender == "Female"){?>selected<?php ;}?>>Female</option>
                    </select>
                    <span class="error_message"></span>
                    <i></i>
                </label>
            </div>
            
            <div class="unit">
                <label class="label">Name</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-anchor"></i>
                    </label>
                    <input name="name" type="text" class="form-control" data-validation="required" data-name="Name" value="{{$client->name}}"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Email</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-envelope"></i>
                    </label>
                    <input name="email" type="text" data-validation="required,email" data-name="Email"  class="form-control" value="{{$client->email}}"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Phone</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-phone"></i>
                    </label>
                    <input name="phone" type="text" data-validation="required,number" data-name="Phone" class="form-control" value="{{$client->phone}}"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Fax</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-phone"></i>
                    </label>
                    <input name="fax" type="text" data-validation="number" data-name="Fax" class="form-control" value="{{$client->fax}}"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Date of birth</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-calendar"></i>
                    </label>
                    <input name="date_of_birth" type="text" data-validation="" data-name="Date of birth" class="form-control datePicker" value="<?php if($client->date_of_birth!= ""){echo date("m/d/Y",strtotime($client->date_of_birth)) ;}?>"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Joining Date</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-calendar"></i>
                    </label>
                    <input autocomplete="off" name="joining_date" type="text" data-validation="required" data-name="Joining Date" class="form-control datePicker" value="<?php if($client->joining_date!= ""){echo date("m/d/Y",strtotime($client->joining_date)) ;}?>"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="hide unit">
                <label class="label">password</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-lock"></i>
                    </label>
                    <input name="password" data-validation="" data-name="password" type="password" class="form-control" value="{{$client->dec_password}}"  >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="hide unit">
                <label class="label">Retype Password</label>
                <div class="input">
                    <label class="icon-right">
                        <i class="fa fa-lock"></i>
                    </label>
                    <input name="password2" data-validation="" data-name="password" type="password" class="form-control" value="{{$client->dec_password}}" >
                    <span class="error_message"></span>
                </div>
            </div>
            <div class="unit">
                <label class="label">Refered By</label>
                <label class="input select">
                    <select name="refered_by" data-validation="" data-name="Mother" class="form-control select2" >
                        <option value="" >Select Client</option>
                        @foreach($clients as $clientx)
                            <option  value="{{$clientx->id}}" <?php if($clientx->id == $client->refered_by){?>selected<?php ;}?>>{{$clientx->name}}</option>
                        @endforeach
                    </select>
                    <span class="error_message"></span>
                    <i></i>
                </label>
            </div>
            <div class="unit">
                <label class="label">Mother</label>
                <label class="input select">
                    <select name="mother_id" data-validation="" data-name="Mother" class="form-control select2" >
                        <option value="" >Select Mother</option>
                        @foreach($mothers as $clientx)
                            <option  value="{{$clientx->id}}" <?php if($clientx->id == $client->mother_id){?>selected<?php ;}?>>{{$clientx->name}}</option>
                        @endforeach
                    </select>
                    <span class="error_message"></span>
                    <i></i>
                </label>
            </div>
            
            <div class="unit">
                <label class="label">Father</label>
                <label class="input select">
                    <select name="father_id" data-validation="" data-name="Father" class="form-control select2" >
                        <option value="" >Select Father</option>
                        @foreach($fathers as $clientx)
                            <option  value="{{$clientx->id}}" <?php if($clientx->id == $client->father_id){?>selected<?php ;}?>>{{$clientx->name}}</option>
                        @endforeach
                    </select>
                    <span class="error_message"></span>
                    <i></i>
                </label>
            </div>
            
            
            
            
            
            
            <input type="hidden" name="id" id="id" value="{{$client->id}}"  data-validation="" data-name="id"  />
    </div>
    <div id="response"></div>
    <div class="footer">
        <button type="submit" class="btn btn-lg color" ><i class="fa fa-edit"></i> Save</button>

    </div>
    <input type="reset" class="hide resetForm" >

</form>

resources/views/clients/list.blade.php
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-color">
            <i class="fa fa-user font-color"></i>Clients
        </div>
        <div class="btn-group pull-right">
                    
                      
                    <a href="{{route('admin.clients.init')}}" class="pjax-link"  >
                        <button type="button" class="btn color" id="add_new" >
                            Add New <i class="fa fa-plus"></i>
                        </button>      
                      </a> 
                      
                                       
                    </div>
    </div>
    <div class="portlet-body">
    <form class="ajax_form" method="post" action="/admin/schedules/recommend">
      <div class="table-toolbar" >
            <div class="row" >
                <div class="col-md-5 hide" >
                	<div class="btn-group">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" >
                   <tr>
                     <td align="left" valign="middle"><select name="course_id" data-validation="Required" data-name="Course" class="form-control select2" style="display:inline;" >
                        <option value="" >Select Course</option>
                        @foreach($courses as $course)
                            <option  value="{{$course->id}}" >{{$course->name}} </option>
                        @endforeach
                    </select></td>
                     <td align="left" valign="middle"><input class="btn green"  type="submit" style="display:inline;" value="Recommend to course" name
                     ="course"    />
                 
 
                     </td>
                   </tr>
                 </table>
                    
                              
                      
                      
                    
                      
                                       
                  </div>    
                </div>
                <div class="col-md-5" >
                    <div class="btn-group">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                   <tr>
                     <td align="left" valign="middle"><select name="schedule_id" data-validation="Required" data-name="Course" class="form-control select2" style="display:inline;" >
                        <option value="" >Select Schedule</option>
                        @foreach($schedules as $schedule)
                            <option  value="{{$schedule->id}}" >
                            <?php if(isset($schedule->getCourse->name)){?>
                            {{$schedule->getCourse->name}} 
                            <?php ;}?>
                            ( {{ Carbon\Carbon::parse($schedule->start_date)->format('d M')    }} )
                            
                            </option>
                        @endforeach
                    </select></td>
                     <td align="left" valign="middle"><input class="btn green"  type="submit" style="display:inline;" value="Recommend to Event" name
                     ="event"    /></td>
                   </tr>
                 </table>
                    
                              
                      
                      
                    
                      
                                       
                  </div>
                </div>
                
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                  <th valign="middle"><input type="checkbox" class="group-checkable"></th>
                  <th valign="middle">
                      Name
                  </th>
                  <th valign="middle">Phone</th>
                  <th valign="middle">Email</th>
                    <th valign="middle">
                        Created at
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($clients as $client)
                <tr class="odd gradeX" id="data-row-{{$client->id}}">
                  <td valign="middle">
                  <input type="checkbox" name="clients[]"  class="table-checkbox"  value="{{$client->id}}" >
                  </td>
                  <td valign="middle">
                      {{$client->name}}
                    </td>
                    <td valign="middle">{{$client->phone}}</td>
                  <td valign="middle">{{$client->email}}</td>
                    <td valign="middle">
                        {{$client->created_at}}
                    </td>
                    <td valign="middle">
                    <a href="{{route('admin.clients.profile',['id'=>$client->id])}}" class="btn color pjax-link" ><i class="fa fa-user"></i> Profile</a>
 						@if(Auth::user()->role_id <= 1)
                        <a href="#" data-action="{{route('admin.clients.delete',['id'=>$client->id])}}"  class="btn red delete_single" ><i class="fa fa-remove"></i> Delete</a> 
                        @endif
                        
                        <a href="{{route('admin.clients.edit',['id'=>$client->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        
                    </td>
                </tr>
                @endforeach

        </table>
        </form>
    </div>
</div>

resources/views/clients/test_details.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Test Details
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">Question</th>
                    <th valign="middle">Student Degree</th>
                    <th valign="middle">Max degree</th>
                    <th valign="middle">Start time</th>
                    <th valign="middle">End time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="odd gradeX" id="data-row-{{$answer->id}}" data-user_id = "{{$answer->id}}">
                    <td valign="middle">
                    {{$answer->getQuestion->content}}
                        
                    </td>
                    <td valign="middle">{{$answer->degree}}</td>
                    <td valign="middle">{{$answer->getQuestion->weight}}</td>
                    <td valign="middle">{{$answer->getEntry->start_time}}</td>
                    <td valign="middle">{{$answer->getEntry->end_time}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/clients/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>