app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');



Route::group(['middleware' => ['auth'], 'prefix' => "admin/clients", 'as' => "admin.clients."], function () {
    Route::get('/', 'clientController@index')->name('index');
    Route::delete('{id}/delete', 'clientController@delete')->name('delete')->middleware('can:super_user');
    Route::get('{id}/edit', 'clientController@edit')->name('edit');
    Route::get('{id}/profile', 'clientController@profile')->name('profile');
    Route::get('init', 'clientController@init')->name('init');
    Route::post('save', 'clientController@save')->name('save');

});

Route::group(['middleware' => ['auth','can:super_user'], 'prefix' => "admin/employees", 'as' => "admin.employees."], function () {
    Route::get('/', 'employeeController@index')->name('index');
    Route::delete('{id}/delete', 'employeeController@delete')->name('delete');
    Route::get('{id}/edit', 'employeeController@edit')->name('edit');
    Route::get('{id}/profile', 'employeeController@profile')->name('profile');
    Route::get('init', 'employeeController@init')->name('init');
    Route::post('save', 'employeeController@save')->name('save');

});
Route::group(['middleware' => ['auth','can:super_user'], 'prefix' => "admin/coins", 'as' => "admin.coins."], function () {
    Route::get('/', 'coinController@index')->name('index');
    Route::delete('{id}/delete', 'coinController@delete')->name('delete');
    Route::get('{id}/edit', 'coinController@edit')->name('edit');
    Route::get('init', 'coinController@init')->name('init');
    Route::post('save', 'coinController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/instructors", 'as' => "admin.instructors."], function () {
    Route::get('/', 'instructorController@index')->name('index');
    Route::delete('{id}/delete', 'instructorController@delete')->name('delete');
    Route::delete('{id}/delete_document', 'instructorController@deleteDocument')->name('delete_document');
    Route::get('{id}/edit', 'instructorController@edit')->name('edit');
    Route::get('init', 'instructorController@init')->name('init');
    Route::get('init_document', 'instructorController@init_document')->name('init_document');
    Route::post('save', 'instructorController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/courses", 'as' => "admin.courses."], function () {
    Route::get('/', 'courseController@index')->name('index');
    Route::delete('{id}/delete', 'courseController@delete')->name('delete');
    Route::get('{id}/edit', 'courseController@edit')->name('edit');
    Route::get('init', 'courseController@init')->name('init');
    Route::post('save', 'courseController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/places", 'as' => "admin.places."], function () {
    Route::get('/', 'placeController@index')->name('index');
    Route::delete('{id}/delete', 'placeController@delete')->name('delete');
    Route::get('{id}/edit', 'placeController@edit')->name('edit');
    Route::get('init', 'placeController@init')->name('init');
    Route::post('save', 'placeController@save')->name('save');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/schedules", 'as' => "admin.schedules."], function () {
    Route::get('/', 'scheduleController@index')->name('index');
    Route::post('/recommend', 'scheduleController@recommend')->name('recommend');
    Route::delete('{id}/delete', 'scheduleController@delete')->name('delete');
    Route::delete('schedule_day/{id}/delete', 'scheduleController@deleteDay')->name('delete');
    
    Route::get('{id}/edit', 'scheduleController@edit')->name('edit');
    Route::get('init', 'scheduleController@init')->name('init');
    Route::post('save', 'scheduleController@save')->name('save');
    Route::get('/{id}/manage', 'scheduleController@manage')->name('manage');
    Route::post('update_interested_status', 'scheduleController@update_interested_status')->name('update_interested_status');
    Route::post('add_payment', 'scheduleController@add_payment')->name('add_payment');
    Route::get('/{schedule_id}/{user_id}/payment_history', 'scheduleController@payment_history')->name('payment_history');
    Route::get('/{user_id}/cancel', 'scheduleController@cancel')->name('cancel')->middleware('can:super_user');
    Route::get('/{schedule_id}/end_transactions', 'scheduleController@endTransactions')->name('end_transactions')->middleware('can:super_user');
    Route::get('/{schedule_id}/reopen_transactions', 'scheduleController@reOpenTransactions')->name('reopen_transactions')->middleware('can:super_user');
    
    
    

});


Route::group(['middleware' => ['auth'], 'prefix' => "admin/consultations", 'as' => "admin.consultations."], function () {
    Route::get('/', 'consultationController@index')->name('index');
    Route::delete('{id}/delete', 'consultationController@delete')->name('delete');
    Route::get('{id}/edit', 'consultationController@edit')->name('edit');
    Route::get('pricing', 'consultationController@pricing')->name('pricing')->middleware('can:super_user');
    Route::post('init', 'consultationController@init')->name('init');
    Route::post('save', 'consultationController@save')->name('save');
    Route::post('save_pricing', 'consultationController@save_pricing')->name('save_pricing')->middleware('can:super_user');
    Route::post('save_audio', 'consultationController@save_audio')->name('save_audio');
    Route::post('add_payment', 'consultationController@add_payment')->name('add_payment');
    Route::post('add_reply', 'consultationController@add_reply')->name('add_reply');
    Route::get('/{consultation_id}/end_transactions', 'consultationController@endTransactions')->name('end_transactions')->middleware('can:super_user');
    Route::get('/{consultation_id}/reopen_transactions', 'consultationController@reOpenTransactions')->name('reopen_transactions')->middleware('can:super_user');

});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/expenses", 'as' => "admin.expenses."], function () {
    Route::get('/', 'expenseController@index')->name('index');
    Route::delete('{id}/delete', 'expenseController@delete')->name('delete');
    Route::get('{id}/edit', 'expenseController@edit')->name('edit');
    Route::get('init', 'expenseController@init')->name('init');
    Route::post('save', 'expenseController@save')->name('save');

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/reports", 'as' => "admin.reports."], function () {
    Route::get('/', 'reportController@index')->name('index');
    

});
Route::group(['middleware' => ['auth'], 'prefix' => "admin/transactions", 'as' => "admin.transactions."], function () {
    Route::delete('{id}/delete', 'transactionController@delete')->name('delete');
    
    Route::get('/{stuff_id}/{stuff_identifier}/{user_id}/payment_history', 'transactionController@payment_history')->name('payment_history');
    
    

});
Route::group( ['middleware' => ['auth'],'prefix' => "files", 'as' => "files."], function () {
                    Route::get('/add', 'memoryController@add')->name('add');
                    Route::post('/endpoint', 'fileController@handle')->name('endpoint');
                    Route::post('/save_file', 'fileController@saveFile')->name('save_file');
                    Route::delete('/endpoint/{file}', 'fileController@handle')->name('delete_endpoint');
                    Route::post('/get_file_info', 'fileController@getFileInfo')->name('get_file_info');
                    
    
//--routes@@files

});
Route::auth();

resources/views/employeess/base.blade.php
<?php 
	$i ="user_requests" ; $j = 2;
 ?>
@extends('admin.master')
@section('plugins_css')
@stop

@section('plugins_js')

@stop

@section('page_js')
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/employees.js')}}"></script>

@endSection

@section('add_inits')

@stop

@section('title')
Employees
@stop

@section('page_title')

@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/employeess/edit_form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" value="{{$candidate->name}}">
                    <input type="hidden" name="id" id="hiddenField" value="{{$candidate->id}}" />
                                                  </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="email" class="form-control" value="{{$candidate->email}}" >
                </div>
                <div class="form-group">
                    <label>Mobile</label>
                    <input name="mobile" class="form-control" value="{{$candidate->phone}}" >
                </div>
                <div class="form-group">
                    <label>Phase</label>
                    <select name="user_phase" class="form-control" >
                    	<option value="testing" <?php if($candidate->user_phase == "testing"){?> selected="selected"<?php ;}?>>Testing</option>
                    	<option value="testEvaluation" <?php if($candidate->user_phase == "testEvaluation"){?> selected="selected"<?php ;}?>>Test Evaluation</option>
                    	<option value="phoneInterview" <?php if($candidate->user_phase == "phoneInterview"){?> selected="selected"<?php ;}?>>Phone Interview</option>
                    	<option value="pilotTest" <?php if($candidate->user_phase == "pilotTest"){?> selected="selected"<?php ;}?>>Pilot Test</option>
                    	<option value="passedAll" <?php if($candidate->user_phase == "passedAll"){?> selected="selected"<?php ;}?>>Passed All</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="user_status" class="form-control" >
                    	<option value="Pending" <?php if($candidate->user_status == "Pending"){?> selected="selected"<?php ;}?>>Pending</option>
                    	<option value="Approved" <?php if($candidate->user_status == "Approved"){?> selected="selected"<?php ;}?>>Approved</option>
                    	<option value="Rejected" <?php if($candidate->user_status == "Rejected"){?> selected="selected"<?php ;}?>>Rejected</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Quiz grade</label>
                    <input name="quiz" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif" >
                </div>
                <div class="form-group">
                    <label>Fluency</label>
                    <input name="fluency" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif" >
                </div>
                <div class="form-group">
                    <label>Vocab</label>
                    <input name="vocab" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif" >
                </div>
                <div class="form-group">
                    <label>Grammar</label>
                    <input name="grammar" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif" >
                </div>
                <div class="form-group">
                    <label>Accent</label>
                    <input name="accent" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif" >
                </div>
                <div class="form-group">
                    <label>Pilot test grade</label>
                    <input name="pilot" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif" >
                </div>
               
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all-edit" data-action="{{route('admin.candidates.saveEdit')}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/employeess/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Employees
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
      <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                    <a href="{{route('admin.employees.init')}}" class="pjax-link" >
                        <button class="btn green" id="add_new" >

                            Add New <i class="fa fa-plus"></i>
                        </button>      
                      </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                  <th valign="middle">
                      Name
                  </th>
                  <th valign="middle">Office</th>
                  <th valign="middle">Manager</th>
                  <th valign="middle">Position</th>
                  <th valign="middle">Role</th>
                  <th valign="middle">Department</th>
                  <th valign="middle">Email</th>
                  <th valign="middle">Phone</th>
                    <th valign="middle">
                        Created at
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($employees as $employee)
                <tr class="odd gradeX" id="data-row-{{$employee->id}}">
                  <td valign="middle">
                      {{$employee->name}}
                    </td>
                  <td valign="middle"><?php if(isset($employee->getOffice->name)){?>{{$employee->getOffice->name}}<?php ;}?></td>
                  <td valign="middle"><?php if(isset($employee->getManager->name)){?>{{$employee->getManager->name}}<?php ;}?></td>
                  <td valign="middle"><?php if(isset($employee->getPosition->name)){?>{{$employee->getPosition->name}}<?php ;}?></td>
                  <td valign="middle"><?php if(isset($employee->getRole->name)){?>{{$employee->getRole->name}}<?php ;}?></td>
                  <td valign="middle"><?php if(isset($employee->getDepartment->name)){?>{{$employee->getDepartment->name}}<?php ;}?></td>
                  <td valign="middle">{{$employee->email}}</td>
                  <td valign="middle">{{$employee->phone}}</td>
                    <td valign="middle">
                        {{$employee->created_at}}
                    </td>
                    <td valign="middle">
                    	<a href="{{route('admin.employees.profile',['id'=>$employee->id])}}" class="btn blue pjax-link" ><i class="fa fa-eye"></i> Profile</a> 
                        <a href="{{route('admin.employees.edit',['id'=>$employee->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        @if(Auth::user()->role_id < $employee->role_id)
                        <a href="#" data-action="{{route('admin.employees.delete',['id'=>$employee->id])}}"  class="btn red delete_single" ><i class="fa fa-remove"></i> Delete</a> 
                        @endif
                    </td>
                </tr>
                @endforeach

        </table>
    </div>
</div>

resources/views/employeess/test_details.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Test Details
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">Question</th>
                    <th valign="middle">Student Degree</th>
                    <th valign="middle">Max degree</th>
                    <th valign="middle">Start time</th>
                    <th valign="middle">End time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="odd gradeX" id="data-row-{{$answer->id}}" data-user_id = "{{$answer->id}}">
                    <td valign="middle">
                    {{$answer->getQuestion->content}}
                        
                    </td>
                    <td valign="middle">{{$answer->degree}}</td>
                    <td valign="middle">{{$answer->getQuestion->weight}}</td>
                    <td valign="middle">{{$answer->getEntry->start_time}}</td>
                    <td valign="middle">{{$answer->getEntry->end_time}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/employeess/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>